name: CI
on: ['push', 'pull_request']
coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
        - name: Coveralls Finished
          uses: coverallsapp/github-action@master
          with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              parallel-finished: true
