name: CI workflow
on: [push, pull_request]
jobs:
    test:
        name: ${{ matrix.node-version }} ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [macOS-latest, ubuntu-latest]
                node-version: [10, 12, 14]
        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install
              run: npm i

            - name: Install Dev
              run: npm i -D

            - name: Tests
              run: npm test
